apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: mygame-server
spec:
  replicas: 5
  template:
    spec:
      ports:
        - name: default
          containerPort: 7777
      health:
        disabled: true
      template:
        spec:
          containers:
            - name: mygame-server
              image: agonesacr.azurecr.io/mygame-server:0.1
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "128m"
                limits:
                  memory: "128Mi"
                  cpu: "128m"
